#!/bin/bash


if [ -d ~/Reports ]
then
	echo "directory exists"
else
	##mkdir -p ~/Reports/2022
	D1=$(date -d "2022-12-31" "+%D")
 	D2=$(date  -d "2022-01-01" "+%D")
	echo "creating your files ...."
	while [ $D1 != $D2 ]
	do
		mkdir -p ~/Reports/2022/$(date -d "$D2" "+%m")
		touch ~/Reports/2022/$(date -d "$D2" "+%m")/$(date -d "$D2" "+%d").xls
		D2=$(date -d "$D2 + 1 day" "+%D")
	done
	echo "your files are created"


fi
######################back up####################
if [ $(date +%H) -ge 12 ] && [ $(date +%H) -le 13 ];
then
	mkdir -p ~/backup
	cp -R ~/Reports/* ~/backup
	echo "backing up your files"
fi


