#!/bin/bash
source ./task2

while true
do
	read -p "choose one of the following numbers:
		 1)check if the user is root
		 2)change ssh port
		 3)disable root login
		 4)add user
                 5)backup home directory
		 6)check if a file exist (bouns) : " S
	case $S in
		1)IS_SUDOER;;
		2)change_port;;
		3)root_disable;;
		4)add_user;;
		5)cron;;
		6)file_check;;
	esac

	read -p "do you want to excute another function [y/n] : " ANS
	if [ $ANS == "n" ];then
		echo "exiting the script .........."
		break
	fi

done
